[package]
name = "wasmtime-types"
version.workspace = true
authors.workspace = true
description = "WebAssembly type definitions for Cranelift"
license = "Apache-2.0 WITH LLVM-exception"
repository = "https://github.com/bytecodealliance/wasmtime"
documentation = "https://docs.rs/wasmtime-types"
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = { workspace = true }
cranelift-entity = { workspace = true, features = ['enable-serde'] }
serde = { workspace = true }
serde_derive = { workspace = true }
smallvec = { workspace = true, features = ["serde"] }
wasmparser = { workspace = true, features = ["validate"] }

[lints]
workspace = true

[features]
std = ['wasmparser/std']
