[package]
name = "classification-component-onnx"
version = "0.1.0"
edition = "2021"
authors = ["The Wasmtime Project Developers"]
readme = "README.md"
publish = false

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "component:classification-component-onnx"

[package.metadata.component.target.dependencies]
"wasi:cli" = { path = "../../../wasi/wit/deps/cli" }
"wasi:io" = { path = "../../../wasi/wit/deps/io" }
"wasi:clocks" = { path = "../../../wasi/wit/deps/clocks" }
"wasi:filesystem" = { path = "../../../wasi/wit/deps/filesystem" }
"wasi:sockets" = { path = "../../../wasi/wit/deps/sockets" }
"wasi:random" = { path = "../../../wasi/wit/deps/random" }
"wasi:nn" = { path = "../../spec/wit/wasi-nn.wit" }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wit-bindgen = { version = "0.16.0", default-features = false, features = ["realloc"] }
image = { version = "0.24.6", default-features = false, features = ["jpeg"] }
ndarray = "0.15.3"



# This crate is built with the wasm32-wasip1 target, so it's separate
# from the main Wasmtime build, so use this directive to exclude it
# from the parent directory's workspace.
[workspace]
