name: ci

on:
  push:
    branches:
      - veriisle
  pull_request:
    branches:
      - veriisle

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build --features cranelift-isle/printer --package 'cranelift-isle*'
      - name: Test
        run: cargo test --features cranelift-isle/printer --package 'cranelift-isle*'

  veri:
    strategy:
      matrix:
        arch: [aarch64, x64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main
      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install CVC5
        working-directory: main/cranelift/isle/veri/veri
        run: |
          mkdir -p "${{ runner.workspace }}/tools/cvc5"
          ./script/install/cvc5.sh -i "${{ runner.workspace }}/tools/cvc5" -t "${RUNNER_TEMP}"
          echo "${{ runner.workspace }}/tools/cvc5/bin" >> $GITHUB_PATH
      - name: Show CVC5 Version
        run: cvc5 --version
      - name: Build
        run: cargo build --release -p cranelift-isle-veri
        working-directory: main
      - name: Verify
        working-directory: main/cranelift/isle/veri/veri
        run: ./script/veri.sh -a ${{ matrix.arch }} -p release -t "${RUNNER_TEMP}" -o "${{ runner.workspace }}/output"
      - uses: actions/upload-artifact@v4
        if: github.event_name == 'push'
        with:
          name: veri-${{ matrix.arch }}
          path: ${{ runner.workspace }}/output/${{ matrix.arch }}.veri
          if-no-files-found: error
          compression-level: 9
