name: explorer

on:
  push:
    branches:
      - veriisle
  workflow_dispatch:
  pull_request:
    branches:
      - veriisle
    paths:
      - '.github/workflows/explorer.yml'
      - 'cranelift/isle/veri/veri/script/explorer.sh'

# Sets permissions to allow deployment to Github Pages.
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Install Tools
        run: sudo apt-get install -y graphviz
      - name: Build Explorer
        working-directory: cranelift/isle/veri/veri
        run: ./script/explorer.sh -o "${{ runner.temp }}/explorer"
        env:
          ISLE_EXPLORER_GRAPHS: 'true'
      - name: Upload artifact
        if: github.event_name != 'pull_request'
        id: upload
        uses: actions/upload-pages-artifact@v2
        with:
          path: ${{ runner.temp }}/explorer
      - name: Deploy to GitHub Pages
        if: steps.upload.outcome == 'success'
        id: deployment
        uses: actions/deploy-pages@v2
