name: veri

on:
  push:
    branches: [ "verify-main" ]
  pull_request:
    branches: [ "verify-main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install Rust
      uses: ./.github/actions/install-rust
    - name: Install Z3
      uses: ./.github/actions/setup-z3
      with:
        version: "4.12.2"
    - name: Build
      run: cargo build --verbose -p veri_ir -p veri_engine
    - name: Test
      # Single thread because Z3 is a memory hog
      run: cargo test --verbose -p veri_ir -p veri_engine -- --test-threads 1
